### PR TITLE
ARM64 Suppport + Bump Obsidian to 1.0.3

### PR DESCRIPTION
**Pull request by Just5KY**
- For the new GH action to work: 
  - Need to add `DOCKERHUB_USERNAME` & `DOCKERHUB_TOKEN` to publish image to Dockerhub
  - Need to uncomment Line 40 to 45, provide `GIT_TOKEN`  &   add ` ghcr.io/${{ github.repository }}` to line 49 of Github action to publish image to ghcr.io

### Fixing 
- #8 
- #10 

Dockerhub ref: https://hub.docker.com/r/justsky/obsidian-remote

### CODE REVIEW

**Comment by Hoempi** [comment]
Ah, good to see. Just started my local Obsidian and realized the update to 1.0.3 and was wondering about my PR to update to 1.0.0. I'll delete that.

**Comment by sytone** [comment]
DOCKERHUB_USERNAME & DOCKERHUB_TOKEN have been added as secrets.

**Comment by sytone** [comment]
secrets.GIT_TOKEN exists by default already. I assume this would replace the existing workflow?

**Comment by Just5KY** [comment]
We always remame the keyword if you are using it for something else
But git.token will store GitHub token and will push the container to ghcr.io

**Comment by sytone** [comment]
ok, given simplicity of this project just going to leave the defaults so you can uncomment the GH section.

**Comment by sytone** [comment]
ill just merge for now to get the docker package out. will fix GHCR later

**Pull request merged**
